version: '3'

services:
  php_container:
    build: ./php
    container_name: php_container
    volumes:
      - ../server:/var/www/html
    ports:
      - 8180:80
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_MEMORY_LIMIT: 500M
      PHP_UPLOAD_MAX_FILESIZE: 256M
      PHP_POST_MAX_SIZE: 256M
      PHP_DISPLAY_ERRORS: 1
    depends_on:
      - mysql_container

  mysql_container:
    build: ./mysql/
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: qazedcwsxrfvasdf
      MYSQL_DATABASE: mysql_db
    ports:
      - 3131:3306
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
